#define the sonar parameters
horizontalFOV: 130.0
transformation: -0.087
verticalAperture: 20.0
sonarRange: 3.0

#define which implmentation we want to match the features
#method: python # options are cpp or python

#do we want to see the feature images from CFAR? turn on to publish
#visFeatures: True

#define the matching paramters
uncertaintyMax: .97
patchSize: 6

#define CFAR for the horizontal sonar
# Real life
tcHorizontal: 40
gcHorizontal: 10
pfaHorizontal: .1
thresholdHorizontal: 65

# Constant false alarm rate (CFAR) params for feature extraction
CFAR:
  Ntc: 40 # number of training cells
  Ngc: 10 # number of guard cells
  Pfa: 0.1 #false alarm rate
  rank: 10 # matrix rank

# point cloud filtering params
filter:
  threshold: 65 # the min CFAR response to be added to the point cloud
  resolution: 0.1 # voxel downsampling res
  radius: 1.0 # outlier rejection radius
  min_points: 5 # outlier rejection min points
  skip: 1 # how often to skip a point cloud, use 1

# the vis params
visualization:
  coordinates: 'cartesian'
  radius: 2
  color: [0, 165, 255]

# Publish sonar feature image -> computationally expensive
sonar_features: True

# are we using compressed imagary
compressed_images: True